apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: tomtest
  labels:
    app: curl
spec:
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl
        image: curlimages/curl:8.1.2
        command: ["tail", "-f", "/dev/null"]
